import type { Metadata } from "next";
import "./globals.css";
import MuiProvider from "@/components/providers/MuiProvider";
import StoreProvider from "@/components/providers/StoreProvider";
import Layout from "@/components/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <StoreProvider>
          <MuiProvider>
            <Layout>{children}</Layout>
          </MuiProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
